services: mongodb
language: node_js
node_js:
- '6'
before_script:
- npm install mocha chai sinon eslint
script:
- npm test
- npm run-script lint
env:
  matrix:
  - STAGE=development NODE_ENV=testing
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  app: nalch-continuum
  on:
    branch: master
    repo: nalch/continuum
  api_key:
    secure: QOjHnmOO9bKaPrdwk4RryyA4N8rAPX+Fc560hpbhZCBgIUe1IaQy48Zq7dFLxHgFxHVAzijCM69d4pqGr7eGI8hgHcpdcbh6YI3e5unw3hGuumdZzASaeZncca5VkLLfFGlZn7KlkUYPgKgagnDQ2Ufe7PjywDhiL7aXIhLucXqp51cW6nuyerbSG0xNINU6RbDH5isiksBNyCXtdKF/5rFtF2NhA7dyQs5p62XFvhCgaqTY2B27YFMiHOqlPZtRaYj/4phPLA75VXuvrRSkFm4dwKqEB1VheL0zDnnpojLs9uMLz6Q5Ir1HaoqgXCmssOkmNxqKYXlApVlmg8LNGXj6BrI1QU3/kRF6YOhpIpyj1kYQo00XJBwp8ODWOCZkrFixSOOXkNVmriX+iKAQ0ZUks2JSUYdW9ka7WEhHDY4B2bk+PwCfbloc9Tuaqcq7oq2YRB/Y+v6G+oRzUyZPSZdoV4P3anTmHL8JMuUayVKoB9Yj7tq5kntCVbDi9WLIm/l3N3iKQq4LI0GTO49AJ50xBHo1v7sxFQk2a+CxVKUNg5Zk/1mrrhHh7GKtJBpBejoahvbpjZqLlzEdZtR3EaU2hG8c311luFgbHSSvBfmU+zHsbBFt9Zezrc4YQNW5KWh/qZ0GbUwgLLst18l7TXsCIUVRUJNCjNd7tNE88zo=
