services: mongodb

language: node_js
node_js:
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  
before_script:
  - npm install mocha chai sinon eslint

script:
  - npm test
  - npm run-script lint

env:
  - STAGE=development
  - TESTING=true