services: mongodb
language: node_js
node_js:
- '6'
before_script:
- npm install mocha chai sinon eslint
script:
- npm test
- npm run-script lint
env:
  matrix:
  - STAGE=development NODE_ENV=testing
  global:
    secure: IyJm6xUJUU7TfQIKScYd/NhbtDuaR9R1IYlT7fD9QgN534srOH0gGF0BIVg+18TmCcln2AXzTBug1G/llJd20fAbc8dZyGg5KDwZpjWzYo6VkblZVC3RgD6INsG0VjeOhc21/SFjP39/bR0/jSbJckKt6H6Tfk9Wlv4/43tUk4oIMSEPAehpQMwVSRX0Ii34ot0Lpzs/iKPYJlAuhuKFzwQa2mnon929eqB1JR5aruE0A0yNxbEY1GwX1JLELniM2CIcCxpTRvj3+r2guc8xVI3FBi0zxbSEqP8gYCIk0bnKrJ2VSPeg6KdSn0nm5VzIbxJz1o2Pb8P0LuMDeIcNbMprVXe4iBLmqS29H1JuWMFUIK1fKeuIyL8SCGy9E03OTaXhlFak782bAVmWO3c+6zfRJFuBlUzDMdy7Dfu26K+v6WBV4TpcZ9ka4nROXPjbGmNAPccEm4d3LJmvFQ4pAhlLU5/RxKceeSuSmTyx6S1UoBf1N84nIzmD1kMJBen7CZXpOCWQdIJJNY434nXdywmxJwxXFWBuE15YZZO3JrGsb6pKaIrfvUW0I8nvTXI1DrUOH9Xd4LMkVua2tIfOXNFRLhItmq8t7pBBdJfrJi/JVrh0l80LrHlx5zeuqCq6NtNgPYiMjLJgBnAkR+/gyvSBPDw7+uLJmgez5EzdyTo=
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: openshift
  user: scholze.kristian@gmail.com
  password:
    secure: "$OPENSHIFT_PASSWORD"
  domain: nalch
  app: continuum
  on:
    branch: master
    repo: nalch/continuum
