nodejsapp:
  build: .
  container_name: nodejs
  links:
   - mongodb
  ports:
   - "8300:8300"
  environment:
   - STAGE=development
  volumes:
   - .:/usr/src/app

mongodb:
  image: mongo:3.2
  container_name: mongodb
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db