version: '2'

services:
  nodejs:
    build: .
    container_name: nodejs
    links:
      - mongodb
    ports:
      - "8300:8300"
    environment:
      - STAGE=docker
    volumes:
      - .:/usr/src/app
    networks:
      - backtier

  mongodb:
    image: mongo:3.2
    container_name: mongodb
    ports:
     - "27017:27017"
    volumes:
     - ./database:/data/db
    networks:
      - backtier

networks:
  backtier:
    driver: bridge
